[package]
name = "pokeshow-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
colored = "2"
image = { version = "0.25", default-features = false, features = ["png"] }
